// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npzyogddxtczjxbfnxrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wenlvZ2RkeHRjemp4YmZueHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzQ2NjQsImV4cCI6MjA1ODgxMDY2NH0.0UrjP2DJDDePPiDgjWqlgkb-g8E_CYSOO8-HlxgvFPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);